name: dcrnn
cl_decay_steps: 2000
filter_type: dual_random_walk
horizon: 12
input_dim: 2
l1_decay: 0
max_diffusion_step: 2
num_rnn_layers: 2
output_dim: 1
rnn_units: 64
use_curriculum_learning: False
kernel_size: 2
num_adjs: 2
order: 1
dropout: 0
global_step: 0
max_grad_norm: 5
max_to_keep: 1
using_adjs: True
enc_input_dim: 2
dec_input_dim: 1