name: informer
enc_in:  7
dec_in:  7
c_out:  7
d_model: 512
embed: 'timeF'
freq: 'time'
dropout: 0.1
seq_len: 96
label_len: 48
pred_len: 96
factor: 5
output_attention: False
n_heads: 8
d_ff: 2048
activation: 'gelu'
e_layers: 2
distil: True
d_layers: 1